new file CoffeMashina
EvgenePirat/NIX_java_education_Brekhuncheko_Evgene pull request #3
Opened 2021-11-16 11:38 UTC by EvgenePirat

Created CoffeMashina, pliz proverte

2021-11-20 14:15 UTC, maxsomochkin requested changes
Перепиши вложенные кейсы. Переименуй все переменные

2021-11-20 14:15 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/CoffeMashina.java
> +    for (;;){
Используй while(true) вместо for и вынеси в отдельный метод

2021-11-20 14:15 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/CoffeMashina.java
> +                switch (n2){
Вложенный свич это зло. Никогда так не делай.

2021-11-20 14:15 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/CoffeMashina.java
> +                        if (w1 >= 250 && c1 >= 16 && d1 > 0){
логику под кейсами выноси в отдельный методы

2021-11-25 15:21 UTC, asrubel commented on src/nix/education/java/coffeemachine/CoffeMashina.java
> +    static int money = 550;
А чего все - статические свойства? Представь себе такое- у тебя сто разных кофемашин, изменились ресурсы в одной - изменились во всех? Кажется такого в жизни не бывает.

2021-11-25 15:34 UTC, asrubel commented on src/nix/education/java/coffeemachine/CoffeMashina.java
> +                if (water >= 250 && coffeezerna >= 16 && cups > 0){
Много вложенного кода и для каждого вида кофе - повторение кода - сделай один метод, который мог работать сразу для всех видов.

2021-11-25 15:37 UTC, asrubel commented on src/nix/education/java/coffeemachine/CoffeMashina.java
> +                    coffeezerna = coffeezerna - 16;
Пиши названия переменных на английском и соблюдай код-стайл

2021-11-25 15:38 UTC, asrubel commented on src/nix/education/java/coffeemachine/CoffeMashina.java
> +    public static void Fill(){
незываешь методы не по код-стайлу - https://google.github.io/styleguide/javaguide.html

2021-11-25 15:38 UTC, asrubel commented on src/nix/education/java/coffeemachine/Colishestvo.java
> +    public void colichestvo(int w1, int m1, int c1, int d1, int money){
Не совсем понимаю - зачем нужен этот класс - здесь только принты

2021-11-25 15:40 UTC, asrubel reviewed
Привет, нарушаешь код-стайл - https://google.github.io/styleguide/javaguide.html
Используй инглиш для названий переменных и методов. Также избавься от бесполезных классов.

2021-12-05 16:30 UTC, asrubel commented on src/nix/education/java/coffeemachine/CoffeMashina.java
> +        boolean a = true;
всю логику спрячь в методы - метод main  не должен это в себе содержать

2021-12-05 16:33 UTC, asrubel commented on src/nix/education/java/coffeemachine/CoffeMashina.java
> +        coffeMashina.coffeebeans = 120;
все начальные значения нужно было бы передать в конструктор или вообще прописать как инициальные в классе

2021-12-05 16:35 UTC, asrubel commented on src/nix/education/java/coffeemachine/CoffeMashina.java
> +    public static void fill(CoffeMashina coffeMashina) {
сделай методы обычными и меняй свойства внутри объетов кофемашины, здесь статика не нужна

2021-12-05 16:38 UTC, asrubel reviewed
У тебя все методы статические - сделай обычный класс со свойствами и манипулируй ими посредством обычных методов.

2021-12-12 22:31 UTC, asrubel approved these changes
Код, ок - но коммиты не сжал

2021-12-13 19:38 UTC, merged