Hangman Project
EvgenePirat/NIX_java_education_Brekhuncheko_Evgene pull request #4
Opened 2021-11-16 15:14 UTC by EvgenePirat

Created Hangman! Proverte pliz

2021-11-20 13:45 UTC, maxsomochkin requested changes

2021-11-20 13:45 UTC, maxsomochkin commented on src/nix/education/java/hangman/twobokv.java
> +public class twobokv {
Имена классов с большой буквы  Twobokv а методы с маленькой и более осмысленные названия.

2021-11-20 13:45 UTC, maxsomochkin commented on src/nix/education/java/hangman/onebokv.java
> +                case "play":
Всю логику под кейсами в отдельные методы.

2021-11-20 13:45 UTC, maxsomochkin commented on src/nix/education/java/hangman/onebokv.java
> +            }
Разбей портянку на отдельные логические блоки и вынеси их в методы

2021-12-01 21:41 UTC, maxsomochkin requested changes

2021-12-01 21:41 UTC, maxsomochkin commented on src/nix/education/java/hangman/Hangman.java
> +public class Hangman {
Создай отдельный класс Hangman без метода main определи туда все статические методы и поля и сделай их нестатическими. А этот класс преименуй в Main и в методе main создай обьект Hangman и с ним уже работай.
Бизнесс логикане должна находиться в методе main

2021-12-01 21:41 UTC, maxsomochkin commented on src/nix/education/java/hangman/Onebokv.java
> +            switch (action) {
Лучше switch помещать в отдельный метод и всю логику под case тоже. Очень тяжело читать такую портянку.

2021-12-01 21:41 UTC, maxsomochkin commented on src/nix/education/java/hangman/Onebokv.java
> +    public static void oneattempt (){
именуй правильно методы, согласно конвенции oneAttempt или attemptOne

2021-12-01 21:41 UTC, maxsomochkin commented on src/nix/education/java/hangman/Onebokv.java
> +    public static void lettercheck (){
checkLetter

2021-12-01 21:41 UTC, maxsomochkin commented on src/nix/education/java/hangman/Onebokv.java
> +    public static void winhangman (){
winHangman

2021-12-01 21:41 UTC, maxsomochkin commented on src/nix/education/java/hangman/Onebokv.java
> +    public void openonebokv() {
openOneBokv - а лучше openOneLetter - чтобы тебя иностранец понял

2021-12-01 21:41 UTC, maxsomochkin commented on src/nix/education/java/hangman/Onebokv.java
> +        while (g) {
Более осмысленные имена переменным и аргументам

2021-12-01 21:41 UTC, maxsomochkin commented on src/nix/education/java/hangman/Onebokv.java
> +                            if (userresponse[i] == letter) {
userResponse - переименуй все переменные согласно конвенции

2021-12-04 10:55 UTC, maxsomochkin requested changes

2021-12-04 10:55 UTC, maxsomochkin commented on src/nix/education/java/hangman/Hangmain.java
> +    public static void hangmainLite(){
Почему все методы статические?

2021-12-04 10:55 UTC, maxsomochkin commented on src/nix/education/java/hangman/Main.java
> +        Hangmain Hangmain = new Hangmain();
Смысл от создания обьекта, если обращение идет не к методу обьекта, а к методу класса? Сделай методы класса нестатическими.

2021-12-04 10:55 UTC, maxsomochkin commented on src/nix/education/java/hangman/OneLetters.java
> +            for (var i = 0; i < userResponse.length; i++) {
Слишком много логики в одном методе можно цик в отдельный метод поместить

2021-12-12 22:32 UTC, asrubel commented on src/nix/education/java/hangman/OneLetters.java
> +    public void openOneLetters() {
пустые строки добавляй между метордами - так читабельнее будет

2021-12-12 22:32 UTC, asrubel approved these changes

2021-12-13 19:39 UTC, merged